# Generated by Django 5.2.8 on 2025-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client (NutriConnect User)'), ('farmer', 'Farmer'), ('ngo', 'NGO Representative'), ('marketplace', 'Marketplace Admin')], default='client', max_length=15),
        ),
    ]
